version: '3'

services:
  mongo-primary:
    image: mongo:4.0
    stdin_open: true
    tty: true
    volumes:
      - ./log/primary:/mongodb/log
      - ./config:/config
    ports:
      - "7017:27017"
    command: mongod --config /config/mongod.conf --replSet mongodb-cluster


services:
  mongo-slave:
    image: mongo:4.0
    stdin_open: true
    tty: true
    volumes:
      - ./log/slave:/mongodb/log
      - ./config:/config
    ports:
      - "7018:27017"
    command: mongod --config /config/mongod.conf --replSet mongodb-cluster

services:
  mongo-arbiter:
    image: mongo:4.0
    stdin_open: true
    tty: true
    volumes:
      - ./log/arbiter:/mongodb/log
      - ./config:/config
    ports:
      - "7019:27017"
    command: mongod --config /config/mongod.conf --replSet mongodb-cluster